name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      force:
        description: "تجاهُل التعديلات المحلية على السيرفر والمتابعة بالنشر؟ (true/false)"
        required: false
        default: "false"

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Preflight check on server (no GITHUB_STEP_SUMMARY writes)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script_stop: true
          script: |
            set -e
            APP_DIR="/root/bilingual-catalog/bilingual-catalog"
            FORCE_RAW="${{ github.event.inputs.force }}"
            FORCE=$(echo "${FORCE_RAW:-false}" | tr '[:upper:]' '[:lower:]' | xargs)
            echo "== FORCE = ${FORCE}"
            cd "$APP_DIR"

            if [ ! -d ".git" ]; then
              echo "::error::$APP_DIR ليس مستودع Git"
              exit 2
            fi

            git fetch --all --prune

            echo "== Local changes (git status --porcelain) =="
            CHANGES_ALL="$(git status --porcelain || true)"
            echo "${CHANGES_ALL}"

            # تجاهل deploy.sh من قرار الإيقاف
            CHANGES_FILTERED="$(echo "${CHANGES_ALL}" | grep -vE '^\?\?\s+deploy\.sh$' || true)"
            COUNT=$(echo "${CHANGES_FILTERED}" | sed '/^\s*$/d' | wc -l | tr -d ' ')
            echo "== Effective changes (excluding deploy.sh): ${COUNT} =="

            if [ "$COUNT" -gt 0 ] && [ "$FORCE" != "true" ]; then
              echo "::error::تم رصد تعديلات محلية على السيرفر. أوقفنا النشر."
              echo "أعد تشغيل الـ workflow واختر force=true للاستمرار رغم التعديلات."
              exit 1
            fi

            echo "✅ لا مانع من المتابعة."

  deploy:
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy script on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script_stop: true
          script: |
            set -e
            # تأكد من ترميز LF ثم نفّذ السكربت
            sed -i 's/\r$//' /root/bilingual-catalog/bilingual-catalog/deploy.sh
            bash /root/bilingual-catalog/bilingual-catalog/deploy.sh
